package com.norwood.wfcore.common.machine;

/**
 * <p>
 * Symbol legend (predicate mapping in {@code WFMachines}):
 * <ul>
 * <li>A = controller (radar)</li>
 * <li>B = Industrial Steam Casing (GCYM)</li>
 * <li>C = Galvanized Steel frame</li>
 * <li>D = Aluminium Sheet Casing also hosts the Energy Input + Data Reception hatches</li>
 * <li>E = Atomic Casing (GCYM)</li>
 * <li>F = Bronze Bricks (steam machine casing)</li>
 * <li>G = Galvanized Steel block</li>
 * <li>H = Boltable Casing (unbolted) dish/tower skin</li>
 * <li>I = Aluminium frame, J = Aluminium block</li>
 * <li>K = Aluminium Sheet Casing on the bottom IO box hosts the Energy Input + Data Reception hatches</li>
 * </ul>
 */
public final class RadarStructure {

    private RadarStructure() {}

    public static final String[][] AISLES = {
            { "   BBB     BBB   ", "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "      HHHHH      ", "      HHHHH      ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "  BBBB     BBBB  ", "    C       C    ", "    C       C    ", "    C       C    ", "    C       C    ",
                    "    C       C    ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "      DDDDD      ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "      HHHHH      ", "    HH     HH    ", "    HH     HH    ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { " BBBBB     BBBBB ", "   C         C   ", "   C         C   ", "   C         C   ", "   C         C   ",
                    "   C         C   ", "    CC     CC    ", "    C CC CC C    ", "    C   C   C    ",
                    "    C CC CC C    ", "    CC     CC    ", "    CDBBBBBDC    ", "    DD     DD    ",
                    "    D       D    ", "    D       D    ", "    E       E    ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "    HHHHHHHHH    ", "   H   I I   H   ", "   H   I I   H   ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "BBBBB       BBBBB", "  C           C  ", "  C           C  ", "  C           C  ", "  C           C  ",
                    "  C           C  ", "                 ", "                 ", "    C       C    ",
                    "    C       C    ", "   CGC     CGC   ", "    GDBBBBBDG    ", "   DGD     DGD   ",
                    "   DCD     DCD   ", "    CD     DC    ", "    CE     EC    ", "    C       C    ",
                    "    C       C    ", "    CC     CC    ", "    C CC CC C    ", "    C   C   C    ",
                    "    C CC CC C    ", "    CC     CC    ", "     CCCCCCC     ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "   HHHHHHHHHHH   ", "  H           H  ", "  H           H  ",
                    "       I I       ", "       I I       ", "        I        ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "BBBBBB     BBBBBB", " C             C ", " C             C ", " C             C ", " C             C ",
                    " C             C ", "  C           C  ", "  C           C  ", "  CC         CC  ",
                    "  CC         CC  ", "  CGC       CGC  ", "  CGDBBBBBBBDGC  ", "  DGD       DGD  ",
                    "  DC         CD  ", "  DC         CD  ", "  EC         CE  ", "   C         C   ",
                    "   C         C   ", "   C         C   ", "   C         C   ", "   C         C   ",
                    "   C         C   ", "   C         C   ", "    C       C    ", "     C EEE C     ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "      HHHHH      ", "  HHHH     HHHH  ", " H             H ", " H             H ",
                    "                 ", "                 ", "       I I       ", "        I        ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "BBB BBB   BBB BBB", "                 ", "                 ", "                 ", "                 ",
                    "                 ", "  C           C  ", "                 ", "                 ",
                    "                 ", "  CC         CC  ", "  DDBBBBBBBBBDD  ", "  DD         DD  ",
                    "   D         D   ", "   D         D   ", "   E         E   ", "                 ",
                    "                 ", "   C         C   ", "                 ", "                 ",
                    "                 ", "   C         C   ", "   C C     C C   ", "    CCEDDDECC    ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "     HHHHHHH     ", "  HHH       HHH  ", " H             H ", " H             H ",
                    "                 ", "                 ", "                 ", "                 ",
                    "        I        ", "        I        ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "     BBBBBBB     ", "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "  C           C  ", "                 ",
                    "  C           C  ", "                 ", " DBBBBBBBBBBBBBD ", "   D             ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "   C         C   ", "                 ",
                    "   C         C   ", "                 ", "   C  C   C  C   ", "     EDDDDDE     ",
                    "                 ", "                 ", "    DD     DD    ", "    DD     DD    ",
                    "    DD     DD    ", "                 ", "                 ", "       HHH       ",
                    "    HHH   HHH    ", " HHH         HHH ", "H               H", "H               H",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "        I        ", "        I        ",
                    "                 ", "                 ", "                 " },
            { "      BBBBB      ", "       KKK       ", "       KKK       ", "       KKK       ", "                 ",
                    "                 ", "                 ", "  C           C  ", "                 ",
                    "  C           C  ", "                 ", " DBBBBBBBBBBBBBD ", "   D             ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "   C         C   ", "                 ",
                    "   C         C   ", "       E         ", "   C   E C   C   ", "    EDDDDDDDE    ",
                    "    DD     DD    ", "    DD     DD    ", "    DD     DD    ", "   CCCCCCCCCCC   ",
                    "    DD  C  DD    ", "    DD  C  DD    ", "        C        ", "      HHHHH      ",
                    "    HH     HH    ", " HHH         HHH ", "H I           I H", "H I           I H",
                    "   I         I   ", "   I         I   ", "    I       I    ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "        I        ", "        J        ", "                 " },
            { "      BBBBB      ", "       EKK       ", "       EFK       ", "       EFK       ", "       EF        ",
                    "       EF        ", "       EF        ", "       EF        ", "  C    EF     C  ",
                    "       EF        ", "       EF        ", " DBBBB EFBBBBBBD ", "   A   EF        ",
                    "       EF        ", "       EF        ", "       EF        ", "       EF        ",
                    "       EF        ", "       EF        ", "       EF        ", "   C   EF    C   ",
                    "       EF        ", "       EF        ", "   C FFFFFFF C   ", "    EFDDDDDFE    ",
                    "    DD     DD    ", "    DD     DD    ", "   CCCCCCCCCCC   ", "   GGGGGGGGGGG   ",
                    "   CCCCCGCCCCC   ", "    DD CGC DD    ", "       CGC       ", "      HHHHH      ",
                    "    HH     HH    ", " HHH         HHH ", "H               H", "H               H",
                    "                 ", "                 ", "   I         I   ", "    I       I    ",
                    "     I     I     ", "     I     I     ", "      I   I      ", "      I   I      ",
                    "       IJI       ", "       JJJ       ", "        J        " },
            { "      BBBBB      ", "       KKK       ", "       KKK       ", "       KKK       ", "                 ",
                    "                 ", "                 ", "  C           C  ", "                 ",
                    "  C           C  ", "                 ", " DBBBBBBBBBBBBBD ", "   D             ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "   C         C   ", "                 ",
                    "   C         C   ", "       E         ", "   C   E C   C   ", "    EDDDDDDDE    ",
                    "    DD     DD    ", "    DD     DD    ", "    DD     DD    ", "   CCCCCCCCCCC   ",
                    "    DD  C  DD    ", "    DD  C  DD    ", "        C        ", "      HHHHH      ",
                    "    HH     HH    ", " HHH         HHH ", "H I           I H", "H I           I H",
                    "   I         I   ", "   I         I   ", "    I       I    ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "        I        ", "        J        ", "                 " },
            { "     BBBBBBB     ", "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "  C           C  ", "                 ",
                    "  C           C  ", "                 ", " DBBBBBBBBBBBBBD ", "   D             ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "   C         C   ", "                 ",
                    "   C         C   ", "                 ", "   C  C   C  C   ", "     EDDDDDE     ",
                    "                 ", "                 ", "    DD     DD    ", "    DD     DD    ",
                    "    DD     DD    ", "                 ", "                 ", "       HHH       ",
                    "    HHH   HHH    ", " HHH         HHH ", "H               H", "H               H",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "        I        ", "        I        ",
                    "                 ", "                 ", "                 " },
            { "BBB BBB   BBB BBB", "                 ", "                 ", "                 ", "                 ",
                    "                 ", "  C           C  ", "                 ", "                 ",
                    "                 ", "  CC         CC  ", "  DDBBBBBBBBBDD  ", "  DD         DD  ",
                    "   D         D   ", "   D         D   ", "   E         E   ", "                 ",
                    "                 ", "   C         C   ", "                 ", "                 ",
                    "                 ", "   C         C   ", "   C C     C C   ", "    CCEDDDECC    ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "     HHHHHHH     ", "  HHH       HHH  ", " H             H ", " H             H ",
                    "                 ", "                 ", "                 ", "                 ",
                    "        I        ", "        I        ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "BBBBBB     BBBBBB", " C             C ", " C             C ", " C             C ", " C             C ",
                    " C             C ", "  C           C  ", "  C           C  ", "  CC         CC  ",
                    "  CC         CC  ", "  CGC       CGC  ", "  CGDBBBBBBBDGC  ", "  DGD       DGD  ",
                    "  DC         CD  ", "  DC         CD  ", "  EC         CE  ", "   C         C   ",
                    "   C         C   ", "   C         C   ", "   C         C   ", "   C         C   ",
                    "   C         C   ", "   C         C   ", "    C       C    ", "     C EEE C     ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "      HHHHH      ", "  HHHH     HHHH  ", " H             H ", " H             H ",
                    "                 ", "                 ", "       I I       ", "        I        ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "BBBBB       BBBBB", "  C           C  ", "  C           C  ", "  C           C  ", "  C           C  ",
                    "  C           C  ", "                 ", "                 ", "    C       C    ",
                    "    C       C    ", "   CGC     CGC   ", "    GDBBBBBDG    ", "   DGD     DGD   ",
                    "   DCD     DCD   ", "    CD     DC    ", "    CE     EC    ", "    C       C    ",
                    "    C       C    ", "    CC     CC    ", "    C CC CC C    ", "    C   C   C    ",
                    "    C CC CC C    ", "    CC     CC    ", "     CCCCCCC     ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "   HHHHHHHHHHH   ", "  H           H  ", "  H           H  ",
                    "       I I       ", "       I I       ", "        I        ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { " BBBBB     BBBBB ", "   C         C   ", "   C         C   ", "   C         C   ", "   C         C   ",
                    "   C         C   ", "    CC     CC    ", "    C CC CC C    ", "    C   C   C    ",
                    "    C CC CC C    ", "    CC     CC    ", "    CDBBBBBDC    ", "    DD     DD    ",
                    "    D       D    ", "    D       D    ", "    E       E    ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "    HHHHHHHHH    ", "   H   I I   H   ", "   H   I I   H   ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "  BBBB     BBBB  ", "    C       C    ", "    C       C    ", "    C       C    ", "    C       C    ",
                    "    C       C    ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "      DDDDD      ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "      HHHHH      ", "    HH     HH    ", "    HH     HH    ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
            { "   BBB     BBB   ", "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "      HHHHH      ", "      HHHHH      ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 ", "                 ",
                    "                 ", "                 ", "                 " },
    };
}
