package com.norwood.wfcore.common.machine;

/**
 * The radar's multiblock structure, ported verbatim from the 1.12.2 controller. 16 aisles, each 47
 * layers of 16 characters. Symbol legend (see {@code WFMachines} for the predicate mapping):
 * <ul>
 * <li>A = controller</li>
 * <li>B = Aluminium block, C = Steel block, D = Lead block</li>
 * <li>E = Aluminium frame, F = Galvanized Steel frame</li>
 * <li>G = concrete (smooth stone), H = red copper (copper block) — HBM substitutes</li>
 * <li>J = bolted boltable casing, K = aluminium sheet casing</li>
 * <li>I = energy input hatch (or aluminium sheet casing)</li>
 * </ul>
 */
public final class RadarStructure {

    private RadarStructure() {}

    public static final String[][] AISLES = {
            { "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "      JJJJ      ", "      JJJJ      ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " GGGCG    GCGGG ", "    F      F    ", "    F      F    ", "    F      F    ", "    F      F    ",
                    "    F      F    ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "      JJJJ      ", "    JJ    JJ    ", "    JJ    JJ    ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " GFCGG    GGCFG ", "   F        F   ", "   F        F   ", "   F        F   ", "   F        F   ",
                    "   F        F   ", "    FF    FF    ", "    F F  F F    ", "    F  FF  F    ", "    F  FF  F    ",
                    "    F F  F F    ", "   KKKKKKKKKK   ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "    JJJJJJJJ    ", "   J   EE   J   ", "   J   EE   J   ",
                    "       EE       ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " GCGG      GGCG ", "  F          F  ", "  F          F  ", "  F          F  ", "  F          F  ",
                    "  F          F  ", "                ", "                ", "                ", "                ",
                    "                ", "  KKGGGGGGGGKK  ", "   GG      GG   ", "    F      F    ", "    FF    FF    ",
                    "    F F  F F    ", "    F  FF  F    ", "    F  FF  F    ", "    F F  F F    ", "    FF    FF    ",
                    "    FFFFFFFF    ", "       FF       ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "   JJJJJJJJJJ   ", "  J          J  ", "  J          J  ",
                    "                ", "       EE       ", "       EE       ", "       EE       ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " CGG        GGC ", " F            F ", " F            F ", " F            F ", " F            F ",
                    " F            F ", "  F          F  ", "  F          F  ", "  F          F  ", "  F          F  ",
                    "  F          F  ", "  KGGGGGGGGGGK  ", "   GG      GG   ", "   F        F   ", "   F        F   ",
                    "   F        F   ", "   F        F   ", "   F        F   ", "   F        F   ", "   F        F   ",
                    "   F        F   ", "    F      F    ", "      KKKK      ", "      KKKK      ", "      KKKK      ",
                    "      KKKK      ", "      KKKK      ", "      KKKK      ", "      KBBK      ", "       KK       ",
                    "                ", "     JJJJJJ     ", "  JJJ      JJJ  ", " J            J ", " J            J ",
                    "                ", "                ", "                ", "                ", "       EE       ",
                    "       EE       ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " GG    KKK   GG ", "       KIK      ", "       KIK      ", "       KKK      ", "                ",
                    "                ", "  F          F  ", "                ", "                ", "                ",
                    "                ", "  KGGGGGGGGGGK  ", "                ", "                ", "   F        F   ",
                    "                ", "                ", "                ", "                ", "   F        F   ",
                    "   F        F   ", "                ", "     FKKHKF     ", "      KKKK      ", "      KKKK      ",
                    "      KKKK      ", "      KKKK      ", "      KKKK      ", "      KBBK      ", "       KK       ",
                    "                ", "    JJJJJJJJ    ", "  JJ        JJ  ", " J            J ", " J            J ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "       EE       ", "       EE       ", "       EE       ", "                ",
                    "                ", "                " },
            { "       KKK      ", "       KHI      ", "       KHI      ", "       KKK      ", "                ",
                    "                ", "                ", "  F          F  ", "                ", "                ",
                    "  F          F  ", "  KGGGGGGGGGGK  ", "           K    ", "                ", "                ",
                    "   F        F   ", "                ", "                ", "   F        F   ", "                ",
                    "   F        F   ", "                ", "    KKKKHKKK    ", "                ", "                ",
                    "      DDDD      ", "       DD       ", "       DD       ", "       BB       ", "       BB       ",
                    "      JJJJ      ", "    JJ    JJ    ", " JJJ        JJJ ", "J              J", "J              J",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "       EE       ",
                    "                ", "                " },
            { "       KKK      ", "       KHI      ", "       KHI      ", "       KHK      ", "        H       ",
                    "        H       ", "        H       ", "        H       ", "  F     H    F  ", "  F     H    F  ",
                    "        H       ", "  KGGGGGHHHHGK  ", "        H  A    ", "        H       ", "        H       ",
                    "        H       ", "   F    H   F   ", "   F    H   F   ", "        H       ", "        H       ",
                    "   F    H   F   ", "   F    H   F   ", "    KKKKHKKK    ", "                ", "                ",
                    "      DDDD      ", "       DD       ", "       DD       ", "       BB       ", "       BB       ",
                    "      JJJJ      ", "    JJ    JJ    ", " JJJ        JJJ ", "J E          E J", "J E          E J",
                    "  E          E  ", "   E        E   ", "   E        E   ", "   E        E   ", "    E      E    ",
                    "    E      E    ", "     E    E     ", "     E    E     ", "     E    E     ", "      E  E      ",
                    "       BB       ", "       BB       " },
            { "       KKK      ", "       KKK      ", "       KKK      ", "       KKK      ", "        K       ",
                    "        K       ", "        K       ", "        K       ", "  F     K    F  ", "  F     K    F  ",
                    "        K       ", "  KGGGGGGGGGGK  ", "           K    ", "                ", "                ",
                    "                ", "   F        F   ", "   F        F   ", "                ", "                ",
                    "   F        F   ", "   F        F   ", "    KKKKKKKK    ", "                ", "                ",
                    "      DDDD      ", "       DD       ", "       DD       ", "       BB       ", "       BB       ",
                    "      JJJJ      ", "    JJ    JJ    ", " JJJ        JJJ ", "J E          E J", "J E          E J",
                    "  E          E  ", "   E        E   ", "   E        E   ", "   E        E   ", "    E      E    ",
                    "    E      E    ", "     E    E     ", "     E    E     ", "     E    E     ", "      E  E      ",
                    "       BB       ", "       BB       " },
            { "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "  F          F  ", "                ", "                ",
                    "  F          F  ", "  KGGGGG GGGGK  ", "           K    ", "                ", "                ",
                    "   F        F   ", "                ", "                ", "   F        F   ", "                ",
                    "   F        F   ", "                ", "    KKKKKKKK    ", "                ", "                ",
                    "      DDDD      ", "       DD       ", "       DD       ", "       BB       ", "       BB       ",
                    "      JJJJ      ", "    JJ    JJ    ", " JJJ        JJJ ", "J              J", "J              J",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "       EE       ",
                    "                ", "                " },
            { " GG          GG ", "                ", "                ", "                ", "                ",
                    "                ", "  F          F  ", "                ", "                ", "                ",
                    "                ", "  KGGGGGGGGGGK  ", "                ", "                ", "   F        F   ",
                    "                ", "                ", "                ", "                ", "   F        F   ",
                    "   F        F   ", "                ", "     FKKKKF     ", "      KKKK      ", "      KKKK      ",
                    "      KKKK      ", "      KKKK      ", "      KKKK      ", "      KBBK      ", "       KK       ",
                    "                ", "    JJJJJJJJ    ", "  JJ        JJ  ", " J            J ", " J            J ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "       EE       ", "       EE       ", "       EE       ", "                ",
                    "                ", "                " },
            { " CGG        GGC ", " F            F ", " F            F ", " F            F ", " F            F ",
                    " F            F ", "  F          F  ", "  F          F  ", "  F          F  ", "  F          F  ",
                    "  F          F  ", "  KGGGGGGGGGGK  ", "   GG      GG   ", "   F        F   ", "   F        F   ",
                    "   F        F   ", "   F        F   ", "   F        F   ", "   F        F   ", "   F        F   ",
                    "   F        F   ", "    F      F    ", "      KKKK      ", "      KKKK      ", "      KKKK      ",
                    "      KKKK      ", "      KKKK      ", "      KKKK      ", "      KBBK      ", "       KK       ",
                    "                ", "     JJJJJJ     ", "  JJJ      JJJ  ", " J            J ", " J            J ",
                    "                ", "                ", "                ", "                ", "       EE       ",
                    "       EE       ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " GCGG      GGCG ", "  F          F  ", "  F          F  ", "  F          F  ", "  F          F  ",
                    "  F          F  ", "                ", "                ", "                ", "                ",
                    "                ", "  KKGGGGGGGGKK  ", "   GG      GG   ", "    F      F    ", "    FF    FF    ",
                    "    F F  F F    ", "    F  FF  F    ", "    F  FF  F    ", "    F F  F F    ", "    FF    FF    ",
                    "    FFFFFFFF    ", "       FF       ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "   JJJJJJJJJJ   ", "  J          J  ", "  J          J  ",
                    "                ", "       EE       ", "       EE       ", "       EE       ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " GFCGG    GGCFG ", "   F        F   ", "   F        F   ", "   F        F   ", "   F        F   ",
                    "   F        F   ", "    FF    FF    ", "    F F  F F    ", "    F  FF  F    ", "    F  FF  F    ",
                    "    F F  F F    ", "   KKKKKKKKKK   ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "    JJJJJJJJ    ", "   J   EE   J   ", "   J   EE   J   ",
                    "       EE       ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { " GGGCG    GCGGG ", "    F      F    ", "    F      F    ", "    F      F    ", "    F      F    ",
                    "    F      F    ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "      JJJJ      ", "    JJ    JJ    ", "    JJ    JJ    ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " },
            { "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "      JJJJ      ", "      JJJJ      ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                ", "                ", "                ", "                ",
                    "                ", "                " }
    };
}
